name: Guestbook Signer

on:
  issues:
    types: [opened]

jobs:
  update-guestbook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Update guestbook in README
        run: |
          python .github/scripts/update_guestbook.py "${{ github.event.issue.user.login }}" "${{ github.event.issue.title }}" "${{ github.event.issue.body }}" "${{ github.event.issue.html_url }}"
      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore: add guestbook entry by ${{ github.event.issue.user.login }}" || echo "No changes to commit"
          git push
      - name: Close the issue
        uses: peter-evans/close-issue@v3
        with:
          comment: "Thank you for signing the guestbook! Your entry has been added. :tada:"
