name: "Sign the Guestbook"
description: "Leave your name and a message to sign the guestbook!"
title: "Guestbook entry: [your name or handle]"
labels: [guestbook]
body:
  - type: input
    id: name
    attributes:
      label: Your Name or GitHub Handle
      description: "How should we display your name in the guestbook?"
      placeholder: "e.g., @yourusername or Jane Doe"
    validations:
      required: true

  - type: textarea
    id: message
    attributes:
      label: Your Message
      description: "What would you like to say to the project or future visitors?"
      placeholder: "e.g., Hello, love this project! 🚀"
    validations:
      required: true
