name: Guestbook Entry
description: Sign the guestbook!
title: "Guestbook: [Your Name]"
labels: ["guestbook"]
body:
  - type: textarea
    id: message
    attributes:
      label: Your Message
      description: "Leave a message in the guestbook!"
    validations:
      required: true
  - type: text
    id: name
    attributes:
      label: "Your Name"
      description: "How would you like to be called?"
    validations:
      required: true
