name: "📫 Add Word to Word Cloud"
description: "Submit a word to be added to the community word cloud"
title: "Add word to word cloud: Need ideas? What would you absolutely put on a programming bumper sticker?"
labels: ["word-cloud"]
body:
  - type: markdown
    attributes:
      value: |
        ### Add a word to the word cloud! Need ideas? What would you absolutely put on a programming bumper sticker?
        
        Your word will be added to the word cloud in my README. Give it a minute or two to update, then reload the page.
  
  - type: input
    id: word
    attributes:
      label: "Word to Add"
      description: "Enter a single word to add to the word cloud 👇"
      placeholder: "Your word goes here. 👉"
    validations:
      required: true
      
  - type: textarea
    id: message
    attributes:
      label: "Optional Message"
      description: "Add a message about why you chose this word (optional)"
      placeholder: "I chose this word because..."
    validations:
      required: false
