name: Check for New Followers

on:
  schedule:
    - cron: '*/5 * * * *'  # Check every 5 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  check-followers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Check for new followers
        uses: actions/github-script@v6
        with:
          script: |
            // Get current followers count from file
            const fs = require('fs');
            const path = './.github/followers_count.txt';
            
            // Create file if it doesn't exist
            if (!fs.existsSync(path)) {
              fs.writeFileSync(path, '0');
            }
            
            // Read current count
            const currentCount = parseInt(fs.readFileSync(path, 'utf8')) || 0;
            
            // Get current followers from GitHub API
            const { data: followers } = await github.rest.users.listFollowersForUser({
              username: 's009900',  // Your GitHub username
              per_page: 1,  // We only need the count
              headers: {
                'X-GitHub-Api-Version': '2022-11-28'
              }
            });
            
            const newCount = followers.length > 0 ? followers[0].total_count : 0;
            
            // If follower count increased, trigger the update workflow
            if (newCount > currentCount) {
              // Update the stored count
              fs.writeFileSync(path, newCount.toString());
              
              // Trigger the update-followers workflow
              await github.rest.repos.createDispatchEvent({
                owner: context.repo.owner,
                repo: context.repo.repo,
                event_type: 'new_follower'
              });
              
              console.log(`New follower detected! Total followers: ${newCount}`);
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
